name: Build and Publish

on: 
  push:
    branches: 
      - master

jobs:
  build:
    env:
      PACKAGE_VERSION: 1.0.3
      FILE_NAME: ${{RJPSoft.HelperExtensions.$PACKAGE_VERSION.nupkg}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test -c Release
    
    - name: Pack
      env:
        PACKAGE: ${{-p:PackageVersion=$PACKAGE_VERSION}}
      run: dotnet pack $PACKAGE -c Release

    - name: Publish
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: dotnet nuget push $FILE_NAME -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json
      working-directory: /home/runner/work/.NETCore3HelperExtensions/.NETCore3HelperExtensions/ExtensionsTests/bin/Release

    - name: Clean
      if: always()
      run: dotnet clean -c Release
