name: Build and Test

on: 
  pull_request:
  push:
    branches-ignore: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Build with dotnet
      run: dotnet build -c Release
      
    - name: Test with dotnet
      run: dotnet test -c Release

    - name: Clean
      if: always()
      run: dotnet clean -c Release
